/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:95ccb98c-ed0e-456e-8150-6ba01a4f3dd6",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_JRI17TJLr",
    "aws_user_pools_web_client_id": "4bm0g0ad0mkn7idsckb5s00aus",
    "oauth": {}
};


export default awsmobile;
